# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v82iHoJNJftnnqWrtv4QU2-9e_C1CdLf
"""

import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud

df = pd.read_csv("Reviews.csv")
df["Score"].value_counts().plot(kind="bar")  # Distribution des notes

#Nettoyer le texte
import spacy
nlp = spacy.load("en_core_web_sm")

def clean_text(text):
    doc = nlp(text)
    return " ".join([token.lemma_ for token in doc if not token.is_stop and token.is_alpha])

import re
from bs4 import BeautifulSoup  # Pour supprimer les balises HTML

